MSEARCH-236 Authority record search - Identifiers search option
folio-org/mod-search pull request #171
Opened 2021-12-07 11:52 UTC by Shans-Kaluhin

### Purpose/Overview:

The purpose of this story is to support Authority record search option by following identifiers:
 Control Number, Library of Congress Control Number, Other standard Identifier and System Control number.  No other identifiers will be searchable.

### Assumptions:

The story assumes that identifiers array contains the fields that are populated with:
* 001
* 010 $a and $z subfields
* 024 with data from all available subfields with the exception of $6 and $8
* 035 System Control Number $a and $z subfields

### Requirements/Scope:
 * Exact match is supported
 ** Search by "81048315" returns only the records that match the search value

 * Left and right hand truncation is supported:
 ** Search by "81048*" - matches records that start with "81048"
 ** Search by "*8315" - matches records that end with "8315"

### Acceptance criteria:
 * User can search by LCCN
 * Exact match returns only the record that matches the searched value
 * Left- and right hand truncations are supported

### Additional Information:
 Structure of LCCN: [https://www.loc.gov/marc/lccn_structure.html] 

2021-12-07 11:57 UTC, Shans-Kaluhin commented on README.md
> +| `identifiers.identifierTypeId` |   term    | `identifiers.identifierTypeId=="123" identifiers.value = "1023*"` | Matches authorities that have an identifier if type `123` with value `1023*`|
Just added here `identifiers.value` and `identifiers.identifierTypeId`

2021-12-08 12:50 UTC, MikhailFokanov approved these changes
Looks good.

2021-12-08 12:50 UTC, MikhailFokanov approved these changes

2021-12-09 12:54 UTC, OleksiiKuzminov approved these changes

2021-12-09 15:52 UTC, pfilippov-epam requested changes
HI, looks good except for a few things
* there is no need to add `identifierTypeId` as a search option, I am not sure that someone will use it and it's missing in acceptance criteria
* story says that search by LCCN must be provided, but currently, it can be performed only using queries like `identifiers.value == lccn` , which is ok, but I think that it's assumed that search option must be `lccn == lccn` (it can be done using searchField functionality)

2021-12-14 09:48 UTC, pfilippov-epam requested changes

2021-12-14 09:48 UTC, pfilippov-epam commented on src/main/java/org/folio/search/service/setter/authority/AbstractIdentifierProcessor.java
> +  private final InstanceReferenceDataService identifierTypeCache;
```suggestion
  private final InstanceReferenceDataService referenceDataService;
```

2021-12-14 09:48 UTC, pfilippov-epam commented on src/main/java/org/folio/search/service/setter/authority/AbstractIdentifierProcessor.java
> +public abstract class AbstractIdentifierProcessor implements FieldProcessor<Authority, Set<String>> {
Maybe there is a way to reuse AbstractIdentifierProcessor from Instance?

2021-12-15 11:22 UTC, pfilippov-epam approved these changes

2021-12-17 15:09 UTC, OleksiiKuzminov approved these changes

2021-12-17 15:30 UTC, MikhailFokanov approved these changes

2021-12-17 16:15 UTC, merged