MSEARCH-469: Update the module to Spring boot v3.0.0 and identify issues.
folio-org/mod-search pull request #327
Opened 2023-01-31 10:30 UTC by MurodjonMukhamadaliev

## Purpose

https://issues.folio.org/browse/MSEARCH-469 :  mod-search: Update the module to Spring boot v3.0.0 and identify issues.

## Approach

Migrating to Spring Boot v3.0.0: https://wiki.folio.org/display/~Taras_Spashchenko/Migration+to+Spring+Boot+v3.0.0+How+to?src=contextnavpagetreemode

### Changes checklist
- [ ] API paths, methods, request or response bodies changed, added, or removed
- [ ] Database schema changes
- [ ] Interface versions changes
- [ ] Interface dependencies added, or removed
- [ ] Permissions changed, added, or removed
- [ ] Check logging.

### TODOS and Open Questions
- [ ] Use GitHub checklists. When solved, check the box and explain the answer.

### Learning
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._

2023-01-31 11:43 UTC, psmagin requested changes

2023-01-31 11:43 UTC, psmagin commented on pom.xml
> +    </dependency>
I believe the dependency is not used.

2023-02-01 08:22 UTC, hasanepam approved these changes

2023-02-02 10:33 UTC, psmagin approved these changes

2023-02-02 12:21 UTC, merged