MSEARCH-557: Small fix
folio-org/mod-search pull request #416
Opened 2023-09-12 11:49 UTC by hasanepam

## Purpose
Fix related to browse in one direction

### Learning
[MSEARCH-557](https://issues.folio.org/browse/MSEARCH-557)

2023-09-12 11:54 UTC, andrei-razumnov approved these changes

2023-09-12 12:55 UTC, psmagin requested changes
Please rename PR with meaningful name. 
Please add test to the case you are fixed, because currently there is no understanding why this fix done.

2023-09-13 21:50 UTC, hasanepam commented on src/main/java/org/folio/search/utils/CallNumberUtils.java
> +          || i.getEffectiveCallNumberComponents().getCallNumber().equals(r.getFullCallNumber()))).toList();
This check is added in order to exclude non-matching call numbers, which an resulting instance, with matching call number, may include.

2023-09-14 09:57 UTC, psmagin approved these changes

2023-09-14 10:00 UTC, merged