MSEARCH-635 Update module descriptor with environment variables
folio-org/mod-search pull request #468
Opened 2023-11-12 20:15 UTC by GeloPakDev1

### Purpose
Update module descriptor with environment variables

### Approach
Go over the README file to add missing variables with description and default values into the ModuleDescriptor-template.json file

2023-11-13 08:47 UTC, TsaghikKhachatryan approved these changes

2023-11-13 14:08 UTC, viacheslavkol commented on descriptors/ModuleDescriptor-template.json
> +        "name": "KAFKA_AUTHORITIES_CONSUMER_PATTERN",
Why only 2 "...CONSUMER_PATTERN" ?
Also values should be provided

2023-11-15 08:57 UTC, psmagin requested changes

2023-11-15 08:57 UTC, psmagin commented on README.md
> +| KAFKA_AUTHORITIES_CONSUMER_PATTERN                 | -                         | Custom subscription pattern for Kafka authority message consumers.
Consumer patterns have default values, please update.

2023-11-15 08:57 UTC, psmagin commented on descriptors/ModuleDescriptor-template.json
> +        "value": "(${folio.environment}\\.)(.*\\.)inventory\\.(instance|holdings-record|item|bound-with)",
Replace all `${folio.environment}` with `folio`

2023-11-16 09:32 UTC, psmagin approved these changes

2023-11-16 09:34 UTC, merged