feat(consortium-search): Implement consolidated items/holdings search
folio-org/mod-search pull request #586
Opened 2024-05-22 15:54 UTC by viacheslavkol

### Purpose
Implement consolidated items/holdings search

### Approach
- Implement endpoints by id
- Implement batch endpoints by ids

### Changes Checklist
- [ ] **API Changes**: Document any API paths, methods, request or response bodies changed, added, or removed.
- [ ] **Database Schema Changes**: Indicate any database schema changes and their impact. Confirm that migration scripts were created.
- [ ] **Interface Version Changes**: Indicate any changes to interface versions.
- [ ] **Interface Dependencies**: Document added or removed dependencies.
- [ ] **Permissions**: Document any changes to permissions.
- [ ] **Logging**: Confirm that logging is appropriately handled.
- [ ] **Unit Testing**: Confirm that changed classes were covered by unit tests.
- [ ] **Integration Testing**: Confirm that changed logic was covered by integration tests.
- [ ] **Manual Testing**: Confirm that changes were tested on local or dev environment.
- [ ] **NEWS**: Confirm that the NEWS file is updated with relevant information about the changes made in this pull request.

### Related Issues
[MSEARCH-759](https://folio-org.atlassian.net/browse/MSEARCH-759)

2024-05-28 11:47 UTC, psmagin requested changes

2024-05-28 11:47 UTC, psmagin commented on descriptors/ModuleDescriptor-template.json
> +            "consortium-search.items.collection.get"
```suggestion
            "consortium-search.holdings.item.get"
```

2024-05-28 11:47 UTC, psmagin commented on descriptors/ModuleDescriptor-template.json
> +            "consortium-search.items.collection.get"
```suggestion
            "consortium-search.items.item.get"
```

2024-05-29 15:25 UTC, mukhiddin-yusuf commented on src/main/java/org/folio/search/controller/SearchConsortiumController.java
> +    var searchRequest = CqlSearchRequest.of(Instance.class, tenant, query, itemIds.size(), 0, true, false, true);
looks like lines 142-146 could be extracted to some method and reused also in batch holdings endpoint for building a query and request

2024-05-29 15:25 UTC, mukhiddin-yusuf commented on src/main/java/org/folio/search/converter/ConsortiumHoldingMapper.java
> +@Component
is it needed to have this as a bean? seems like we can just have it as a utility class (and also ConsortiumItemMapper)

2024-05-30 11:04 UTC, mukhiddin-yusuf approved these changes

2024-05-30 11:21 UTC, viacheslavpoliakov approved these changes

2024-05-30 11:21 UTC, viacheslavpoliakov commented on src/main/java/org/folio/search/controller/SearchConsortiumController.java
> +  }
I don't like methods like doSomeAndDoSomeAnd...
May be better way to do something like next
```
private String getVerifiedTenant(String tenantHeader) {
    verifyTenant(tenantHeader)
    return consortiumTenantService.getCentralTenant(tenantHeader).get();
}

private void verifyTenant(String tenantHeader) {
    var centralTenant = consortiumTenantService.getCentralTenant(tenantHeader);
    if (centralTenant.isEmpty() || !centralTenant.get().equals(tenantHeader)) {
      throw new RequestValidationException(REQUEST_NOT_ALLOWED_MSG, XOkapiHeaders.TENANT, tenantHeader);
    }
}
```

2024-05-30 13:36 UTC, merged