[MSEARCH-772]. Return Unified List of Inventory Libraries in a Consortium
folio-org/mod-search pull request #613
Opened 2024-06-27 11:13 UTC by BKadirkhodjaev

### Purpose
Return Unified List of Inventory Libraries in a Consortium ([MSEARCH-772](<https://folio-org.atlassian.net/browse/MSEARCH-772>))

### Approach
- Add new path GET /search/consortium/libraries
- Add filtering by tenant, sort by id, name and tenant id with pagination (limit & offset)
- Add code generation files
- Add unit and integration tests
- Test manually using mod-search, mod-inventory-storage (master branch), Postman, Kafka-UI, Elasticsearch, Kibana (please follow the Jira ticket to see the test output).

### Changes Checklist
- [x] **API Changes**: Document any API paths, methods, request or response bodies changed, added, or removed.
- [ ] **Database Schema Changes**: Indicate any database schema changes and their impact. Confirm that migration scripts were created.
- [ ] **Interface Version Changes**: Indicate any changes to interface versions.
- [ ] **Interface Dependencies**: Document added or removed dependencies.
- [x] **Permissions**: Document any changes to permissions.
- [ ] **Logging**: Confirm that logging is appropriately handled.
- [x] **Unit Testing**: Confirm that changed classes were covered by unit tests.
- [x] **Integration Testing**: Confirm that changed logic was covered by integration tests.
- [x] **Manual Testing**: Confirm that changes were tested on local or dev environment.
- [x] **NEWS**: Confirm that the NEWS file is updated with relevant information about the changes made in this pull request.

### Related Issues
Return Unified List of Inventory Locations in a Consortium ([MSEARCH-681](<https://folio-org.atlassian.net/browse/MSEARCH-681>))
Return Unified List of Inventory Campuses in a Consortium ([MSEARCH-773](<https://folio-org.atlassian.net/browse/MSEARCH-773>))

2024-06-27 11:19 UTC, BKadirkhodjaev commented on src/test/resources/samples/campus-sample/campuses.json
> +    "institutionId": "62cf76b7-cca5-4d33-9217-edf42ce1a848",
Fixed a typo missed in previous PR, it is non-functional

2024-06-27 11:25 UTC, SerhiiNosko approved these changes

2024-06-27 15:03 UTC, mukhiddin-yusuf requested changes

2024-06-27 19:08 UTC, BKadirkhodjaev commented on src/main/resources/swagger.api/parameters/consortium-libraries-limit-param.yaml
> +  default: 1000
I made a separate location-unit-limit-param only for location-units (institutions, campuses and libraries) without affecting locations

2024-06-28 10:53 UTC, mukhiddin-yusuf approved these changes

2024-06-28 11:33 UTC, merged