MSEARCH-793: Make DB Changes for Reindex Merge
folio-org/mod-search pull request #628
Opened 2024-07-17 15:56 UTC by mukhiddin-yusuf

### Purpose
_Make DB Changes for Reindex Merge_

### Approach
_Create migration scripts to create DB tables, view and triggers_

### Changes Checklist
- [ ] **API Changes**: Document any API paths, methods, request or response bodies changed, added, or removed.
- [ ] **Database Schema Changes**: Indicate any database schema changes and their impact. Confirm that migration scripts were created.
- [ ] **Interface Version Changes**: Indicate any changes to interface versions.
- [ ] **Interface Dependencies**: Document added or removed dependencies.
- [ ] **Permissions**: Document any changes to permissions.
- [ ] **Logging**: Confirm that logging is appropriately handled.
- [ ] **Unit Testing**: Confirm that changed classes were covered by unit tests.
- [ ] **Integration Testing**: Confirm that changed logic was covered by integration tests.
- [ ] **Manual Testing**: Confirm that changes were tested on local or dev environment.
- [ ] **NEWS**: Confirm that the NEWS file is updated with relevant information about the changes made in this pull request.

### Related Issues
_List any Jira issues related to this pull request._
[MSEARCH-XXX](https://folio-org.atlassian.net/browse/MSEARCH-XXX)

### Learning and Resources (if applicable)
_Discuss any research conducted during the development of this pull request. Include links to relevant blog posts, patterns, libraries, or addons that were used to solve the problem._

### Screenshots (if applicable)
_If this pull request involves any visual changes or new features, consider including screenshots or GIFs to illustrate the changes._

2024-07-18 15:41 UTC, viacheslavkol commented
Don't we need to fill range tables right away?

2024-07-19 05:28 UTC, mukhiddin-yusuf commented
> Don't we need to fill range tables right away?

if I get it correctly, then no, it would be handled separately in https://folio-org.atlassian.net/browse/MSEARCH-794 or https://folio-org.atlassian.net/browse/MSEARCH-799

2024-07-19 11:36 UTC, psmagin requested changes

2024-07-19 11:36 UTC, psmagin commented on src/main/resources/changelog/changes/v3.3/create-reindex-entity-tables.xml
> +      <column name="instance_id" type="VARCHAR(255)">
Let's make it UUID type

2024-07-19 11:36 UTC, psmagin commented on src/main/resources/changelog/changes/v3.3/create-reindex-entity-tables.xml
> +    <createTable tableName="instances">
It's better to name DB tables in singular

2024-07-19 11:36 UTC, psmagin commented on src/main/resources/changelog/changes/v3.3/create-reindex-entity-tables.xml
> +    <createTable tableName="holdings">
Singular and UUIDs as PK and FK

2024-07-19 11:36 UTC, psmagin commented on src/main/resources/changelog/changes/v3.3/create-reindex-entity-tables.xml
> +    <createTable tableName="items">
Singular and UUIDs as PK and FK

2024-07-19 11:36 UTC, psmagin commented on src/main/resources/changelog/changes/v3.3/create-reindex-entity-tables.xml
> +  <changeSet id="MSEARCH-793@@create-idx_holdings_instance_id" author="Mukhiddin_Yusupov">
Let's move creating indexes into creating table changes to make it one transaction.

2024-07-19 11:36 UTC, psmagin commented on src/main/resources/changelog/changes/v3.3/create-reindex-entity-tables.xml
> +    <createTable tableName="classifications">
Add additional id PK column. We should generate it similar to subjects and contributors.

2024-07-19 11:36 UTC, psmagin commented on src/main/resources/changelog/changes/v3.3/create-reindex-entity-tables.xml
> +      <column name="subject_id" type="VARCHAR(255)">
Let's decrease amount of chars for subject_id and for auhtority_id

2024-07-19 11:36 UTC, psmagin commented on src/main/resources/changelog/changes/v3.3/create-reindex-entity-tables.xml
> +    </createTable>
It should follow same structure as the index: 
```
"name": {
      "index": "keyword_lowercase",
      "showInResponse": [ "browse" ]
    },
    "contributorNameTypeId": {
      "index": "keyword",
      "searchTypes": [ "facet", "filter" ],
      "showInResponse": [ "browse" ]
    },
    "instances": {
      "type": "object",
      "properties": {
        "instanceId": {
          "index": "source"
        },
        "contributorTypeId": {
          "index": "keyword",
          "showInResponse": [ "browse" ]
        },
        "tenantId": {
          "index": "keyword",
          "searchTypes": [ "facet", "filter" ]
        },
        "shared": {
          "index": "bool",
          "searchTypes": [ "facet", "filter" ],
          "default": false
        }
      }
    },
    "authorityId": {
      "index": "keyword",
      "showInResponse": [ "browse" ]
    }
  }
```
`contributorNameTypeId` column is missing. And also please check trigger

2024-07-19 11:36 UTC, psmagin commented on src/main/resources/changelog/changes/v3.3/create-reindex-entity-tables.xml
> +        <constraints nullable="false" primaryKey="true" primaryKeyName="pk_merge_ranges"/>
Let's decrease size

2024-07-19 11:36 UTC, psmagin commented on src/main/resources/changelog/changelog-master.xml
> +  <include file="changes/v3.3/create-reindex-entity-tables.xml" relativeToChangelogFile="true"/>
Let's have v4.0 and update the version in pom.xml

2024-07-22 08:30 UTC, psmagin commented on src/main/resources/changelog/changes/v4.0/create-instance-trigger.sql
>      VALUES (encode(digest((i ->> 'name' || i ->> 'authorityId')::bytea, 'sha1'), 'hex'), -- requires pgcrypto enabled
Id should include contributorNameTypeId

2024-07-22 08:37 UTC, psmagin approved these changes

2024-07-22 14:25 UTC, viacheslavpoliakov approved these changes

2024-07-22 14:27 UTC, merged