[MSEARCH-809] Extend batch holdings search endpoint with filtering by instanceId
folio-org/mod-search pull request #638
Opened 2024-08-05 14:50 UTC by Saba-Zedginidze-EPAM

### Purpose
[[MSEARCH-809] Extend batch holdings search endpoint with filtering by instanceId](https://folio-org.atlassian.net/browse/MSEARCH-809)

### Approach
- Add instanceId as an identifier type

2024-08-07 09:10 UTC, BKadirkhodjaev approved these changes

2024-08-07 15:09 UTC, mukhiddin-yusuf requested changes
@Saba-Zedginidze-EPAM, please make sure that the issues listed in [MSEARCH-815](https://folio-org.atlassian.net/browse/MSEARCH-815) are not related to your changes or your changes may produce the same issues

2024-08-14 09:25 UTC, Saba-Zedginidze-EPAM commented
@mukhiddin-yusuf Issues with `formerIds` and `accessionNumber` were present with the changes of current PR while searching for items and holdings that are located in member tenant from central one. However, the OpenSearch exceptions went away after reindexing

1) 
![image](https://github.com/user-attachments/assets/0033f9bb-c0e3-467a-8867-7cfa98806532)

2)
![image](https://github.com/user-attachments/assets/74ea01c6-84f8-4f29-a61c-5752056577cd)

3)
![image](https://github.com/user-attachments/assets/6fc59738-0e6d-498e-82ea-0fb0a907afb2)

4)
![image](https://github.com/user-attachments/assets/47b5c98a-161b-41dc-b46e-86bbc3a45630)

2024-08-14 09:55 UTC, SerhiiNosko approved these changes

2024-08-14 12:18 UTC, mukhiddin-yusuf approved these changes

2024-08-14 12:20 UTC, merged